<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import { useI18n, type Locale } from '../i18n'
const { locale, t, setLocale } = useI18n(); const open = ref(false); const query = ref(''); const searchInput = ref<HTMLInputElement | null>(null)
const languages = computed(() => [{ code:'zh-TW' as Locale, title:t.value.traditionalChinese, subtitle:t.value.traditionalChineseNative, marker:'繁' }, { code:'en' as Locale, title:t.value.english, subtitle:t.value.englishNative, marker:'A' }])
const matches = computed(() => { const term=query.value.trim().toLocaleLowerCase(locale.value); return languages.value.filter(item => !term || `${item.code} ${item.title} ${item.subtitle}`.toLocaleLowerCase(locale.value).includes(term)) })
function close(){open.value=false;query.value=''};function openDialog(){open.value=true;nextTick(()=>searchInput.value?.focus())};function choose(value:Locale){setLocale(value);close()};function onKey(event:KeyboardEvent){if(event.key==='Escape'&&open.value)close()}
onMounted(()=>window.addEventListener('keydown',onKey));onBeforeUnmount(()=>window.removeEventListener('keydown',onKey))
</script>
<template><button class="language-trigger" type="button" :aria-expanded="open" @click="openDialog"><svg class="globe-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.5 2.5 3.8 5.5 3.8 9S14.5 18.5 12 21M12 3C9.5 5.5 8.2 8.5 8.2 12S9.5 18.5 12 21"/></svg><span>{{locale==='en'?t.english:t.traditionalChinese}}</span><svg class="language-chevron" viewBox="0 0 24 24" aria-hidden="true"><path d="m7 10 5 5 5-5"/></svg></button><Teleport to="body"><div v-if="open" class="modal-backdrop language-backdrop" @click.self="close"><section class="language-modal" role="dialog" aria-modal="true" :aria-label="t.chooseLanguage"><header><div class="language-heading"><span class="language-icon"><svg class="globe-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.5 2.5 3.8 5.5 3.8 9S14.5 18.5 12 21M12 3C9.5 5.5 8.2 8.5 8.2 12S9.5 18.5 12 21"/></svg></span><div><h2>{{t.chooseLanguage}}</h2><p>{{t.chooseLanguageDesc}}</p></div></div><button class="modal-close" type="button" :aria-label="t.close" @click="close">×</button></header><div class="language-modal-body"><label class="language-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg><input ref="searchInput" v-model="query" :placeholder="t.searchLanguage"></label><div v-if="matches.length" class="language-options"><button v-for="item in matches" :key="item.code" type="button" :class="{selected:locale===item.code}" role="option" :aria-selected="locale===item.code" @click="choose(item.code)"><span class="language-option-icon">{{item.marker}}</span><span><strong>{{item.title}}</strong><small>{{item.subtitle}}</small></span><span class="selection-indicator"><svg v-if="locale===item.code" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4.2 4.2L19 6.8"/></svg></span></button></div><p v-else class="language-empty">{{t.noLanguage}}</p></div></section></div></Teleport></template>
