import type { MessageKey } from './zh-TW'

export const en: Record<MessageKey, string> = {
  appName:'SubFlow',workspace:'Workspace',overview:'Overview',personalLedger:'Personal ledger',groups:'Groups',accountSettings:'Account settings',logout:'Sign out',personalGroupFinance:'Personal & group accounting',syncing:'Syncing',forbidden:'You do not have access to this group.',refresh:'Refresh',retry:'Retry',unexpectedError:'An unexpected error occurred',routeError:'Unable to load this page',routeErrorDesc:'This page cannot be displayed right now. Retry or return to the dashboard.',backToDashboard:'Back to dashboard',
  profile:'Profile',profileDesc:'Manage your personal information and display preferences.',email:'Email',displayName:'Display name',timezone:'Time zone',save:'Save settings',saveChanges:'Save changes',saved:'Saved',searchTimezone:'Search time zones or cities…',noTimezone:'No matching time zones',currentTimezone:'Current time zone',language:'Language',chooseLanguage:'Choose language',chooseLanguageDesc:'Choose the language used by SubFlow.',traditionalChinese:'Traditional Chinese',traditionalChineseNative:'繁體中文',english:'English',englishNative:'English',close:'Close',searchLanguage:'Search languages…',noLanguage:'No matching languages',theme:'Appearance',themeDesc:'Choose how the interface is displayed.',systemTheme:'Follow system',lightTheme:'Light',darkTheme:'Dark',switchToLight:'Switch to light mode',switchToDark:'Switch to dark mode',accountInfo:'Account information',appearance:'Appearance',userFallback:'User',notSignedIn:'Not signed in',
  login:'Log in',register:'Create account',welcomeBack:'Welcome back',startSubFlow:'Get started with SubFlow',sharedFinance:'Shared finance, made clear',sharedFinanceDesc:'Manage expenses, subscriptions, and shared finances together.',sharedMoneyClearly:'Shared money, clearly',password:'Password',processing:'Processing…',loginFailed:'Unable to sign in',
  dashboardPersonal:'Personal overview',dashboardAll:'All groups overview',dashboardGroup:'Group overview',dashboardDesc:'View finances for yourself, one group, or every group.',addExpense:'Add expense',personal:'Personal',singleGroup:'Single group',currentGroup:'Current group',allGroups:'All groups',chooseGroup:'Choose a group',previousMonth:'Previous month',nextMonth:'Next month',currentMonth:'This month',cashOutflow:'Cash outflow',personalShare:'Your share',reimbursable:'To recover',monthlySubscription:'Monthly subscriptions',activeSubscriptions:'Active subscriptions',charges:'Charges',thisMonth:'This month',upcoming:'Upcoming charges',manageSubscriptions:'Manage subscriptions',noUpcoming:'No upcoming charges',noUpcomingDesc:'Add a subscription to see upcoming charges here.',noSummary:'No summary data yet',balanceAsOfMonth:'Balance at month end',receivable:'Receivable',payable:'Payable',settled:'Settled',source:'Source',privateRecord:'Private',
  groupSpace:'Group spaces',groupSpaceDesc:'Each family, trip, or team has its own ledger.',yourGroups:'Your groups',noDescription:'No description',edit:'Edit',noGroups:'No groups yet',noGroupsDesc:'Create your first group to start sharing expenses.',editGroup:'Edit group',createGroup:'Create group',groupName:'Group name',groupNamePlaceholder:'e.g. Our home',groupDescription:'Short description',groupDescriptionPlaceholder:'This group is for…',currency:'Currency',color:'Color',cancel:'Cancel',deleteGroup:'Delete group',deleteGroupConfirm:'Delete “{name}”? This cannot be undone.',openGroup:'Open group',allGroupsLink:'All groups',groupWorkspace:'Group workspace',groupWorkspaceDesc:'Manage shared expenses, subscriptions, members, and settings.',groupOverview:'Group overview',splitExpenses:'Expenses & splits',subscriptions:'Subscriptions',members:'Members',settings:'Settings',
  expensePersonal:'Personal expenses',expenseGroup:'Shared expenses',expenseDesc:'Record expenses and keep every cost in view.',recentExpenses:'Recent expenses',records:'{count} records',uncategorized:'Uncategorized',noExpenses:'No expenses yet',noExpensesDesc:'Add your first expense to get started.',editExpense:'Edit expense',createExpense:'Add expense',item:'Item',itemPlaceholder:'e.g. Lunch',category:'Category',amount:'Amount',payer:'Paid by',myself:'Myself',date:'Date',notes:'Notes',remove:'Remove',removeExpenseConfirm:'Remove “{name}”?',sharedRecordWarning:'This record comes from “{group}”. Saving will update the group ledger.',splitMode:'Split method',splitEqual:'Equal',splitAmount:'Fixed amounts',splitPercentage:'Percentage',participants:'Participants',splitTotal:'Split total',splitRemainder:'Remainder',splitValid:'Split totals are valid',splitInvalidAmount:'The split total must equal the expense amount',splitInvalidPercentage:'Percentages must total 100%',basisPointsHint:'Enter a percentage',
  subscriptionPersonal:'Personal subscriptions',subscriptionGroup:'Group subscriptions',subscriptionDesc:'Billing is calculated from the first billing date and can be scheduled to stop.',allSubscriptions:'All subscriptions',noSubscriptions:'No subscriptions yet',noSubscriptionsDesc:'Add your first recurring charge.',editSubscription:'Edit subscription',createSubscription:'Add subscription',name:'Name',namePlaceholder:'e.g. Netflix',cycle:'Cycle',status:'Status',monthly:'Monthly',quarterly:'Quarterly',yearly:'Yearly',firstBilling:'First billing date',nextBilling:'Next billing',stop:'Stop subscription',cancelStop:'Cancel scheduled stop',stopSubscription:'Schedule subscription stop',chooseFinalBilling:'Choose the final billing date',loadMore:'Load more dates',noBillingDates:'No billing dates available',finalBilling:'Final billing',deleteSubscriptionConfirm:'Delete “{name}”?',active:'Active',paused:'Paused',cancelled:'Cancelled',ending:'Ending',ended:'Ended',
  membersInvites:'Members & invitations',membersDesc:'Invitation links are valid for seven days and can be accepted once by the matching email.',groupMembers:'Group members',unnamedMember:'Unnamed member',owner:'Owner',member:'Member',thisMember:'this member',removeMemberConfirm:'Remove “{name}”?',noMemberData:'No member data',noMemberDataDesc:'Enter a group to view its members.',inviteMember:'Invite a member',sendInvitation:'Send invitation',invitationHistory:'Invitation history',resend:'Resend',revoke:'Revoke',noInvitations:'No invitations yet.',memberManagement:'Member management',ownerOnly:'Only the group owner can invite or remove members.',developmentLink:'Development test link',pending:'Pending',deliveryFailed:'Delivery failed',accepted:'Accepted',revoked:'Revoked',expired:'Expired',invitation:'Invitation',joinGroup:'Join a SubFlow group',inviteDesc:'The app verifies that the signed-in email matches the invitation.',acceptInvitation:'Accept invitation',joined:'Joined; going to the group…',
  balances:'Member balances',settlements:'Repayment history',recordSettlement:'Record repayment',fromMember:'Paid by',toMember:'Received by',settlementDate:'Repayment date',noSettlements:'No repayments yet',noBalances:'Everyone is settled up',deleteSettlementConfirm:'Delete this repayment?',
  confirm:'Confirm',delete:'Delete',networkError:'Network connection failed. Please try again.',invalidResponse:'The server returned an invalid response.',requestFailed:'Request failed',invalidRequest:'Please check the information you entered.',conflict:'The data has changed. Please refresh and try again.',notFound:'The requested resource was not found.',internalError:'The service cannot process this request right now.',forbiddenError:'You do not have permission to do that.',
  languageZhMarker:'繁',languageEnMarker:'A',groupTimezone:'Group time zone',groupTimezoneDesc:'Group months, subscription cycles, and shared accounting use this time zone.',originalTimezone:'Original group time: {date} · {timezone}',yourTimezone:'Your time zone: {timezone}',groupTimezoneValue:'Group accounting time zone: {timezone}',
}
