export const zhTW = {
  appName: 'SubFlow', workspace: '工作空間', overview: '總覽', personalLedger: '個人帳本', groups: '群組', accountSettings: '帳號設定', logout: '登出', personalGroupFinance: '個人與群組記帳', syncing: '同步中', forbidden: '你沒有權限查看目前群組。', refresh: '重新整理', retry: '重試', unexpectedError: '發生未預期錯誤', routeError: '頁面載入失敗', routeErrorDesc: '這個頁面暫時無法顯示，請重試或返回總覽。', backToDashboard: '返回總覽',
  profile: '個人設定', profileDesc: '管理你的個人資料與顯示偏好。', email: 'Email', displayName: '顯示名稱', timezone: '時區', save: '儲存設定', saveChanges: '儲存變更', saved: '已儲存', searchTimezone: '搜尋時區或城市…', noTimezone: '找不到符合的時區', currentTimezone: '目前時區', language: '語言', chooseLanguage: '選擇語言', chooseLanguageDesc: '選擇 SubFlow 介面使用的語言。', traditionalChinese: '繁體中文', traditionalChineseNative: '繁體中文', english: 'English', englishNative: '英文', close: '關閉', searchLanguage: '搜尋語言…', noLanguage: '找不到符合的語言', theme: '外觀主題', themeDesc: '選擇介面的顯示模式。', systemTheme: '跟隨系統', lightTheme: '明亮模式', darkTheme: '深色模式', switchToLight: '切換為明亮模式', switchToDark: '切換為深色模式', accountInfo: '帳號資料', appearance: '外觀', userFallback: '使用者', notSignedIn: '尚未登入',
  login: '登入', register: '建立帳號', welcomeBack: '歡迎回來', startSubFlow: '開始使用 SubFlow', sharedFinance: '共享財務，清楚管理', sharedFinanceDesc: '與團隊一起管理支出、訂閱與共同財務。', sharedMoneyClearly: '共享財務，清楚管理', password: '密碼', processing: '處理中…', loginFailed: '無法登入',
  dashboardPersonal: '個人財務總覽', dashboardAll: '所有群組總覽', dashboardGroup: '群組總覽', dashboardDesc: '依個人、單一群組或所有群組查看財務資訊。', addExpense: '新增支出', personal: '個人', singleGroup: '單一群組', currentGroup: '目前群組', allGroups: '所有群組', chooseGroup: '選擇群組', previousMonth: '上個月', nextMonth: '下個月', currentMonth: '本月', cashOutflow: '現金流出', personalShare: '本人份額', reimbursable: '待收回', monthlySubscription: '訂閱月均額', activeSubscriptions: '啟用中訂閱', charges: '扣款數量', thisMonth: '本月', upcoming: '即將扣款', manageSubscriptions: '管理訂閱', noUpcoming: '近期沒有扣款', noUpcomingDesc: '新增訂閱後，近期扣款會出現在這裡。', noSummary: '尚無摘要資料', balanceAsOfMonth: '截至月底餘額', receivable: '應收', payable: '應付', settled: '已結清', source: '來源', privateRecord: '私人',
  groupSpace: '群組空間', groupSpaceDesc: '不同家庭、旅程或團隊可以各自擁有獨立帳本。', yourGroups: '你的群組', noDescription: '尚無說明', edit: '編輯', noGroups: '尚未建立群組。', noGroupsDesc: '建立第一個群組，開始共同記帳與分帳。', editGroup: '編輯群組', createGroup: '建立新群組', groupName: '群組名稱', groupNamePlaceholder: '例如：我們家', groupDescription: '簡短說明', groupDescriptionPlaceholder: '這個群組用來管理…', currency: '幣別', color: '代表色', cancel: '取消', deleteGroup: '刪除群組', deleteGroupConfirm: '確定刪除「{name}」？此操作無法復原。', openGroup: '進入群組', allGroupsLink: '所有群組', groupWorkspace: '群組工作區', groupWorkspaceDesc: '管理共同支出、訂閱、成員與群組設定。', groupOverview: '群組總覽', splitExpenses: '支出與分帳', subscriptions: '訂閱', members: '成員', settings: '設定',
  expensePersonal: '個人支出', expenseGroup: '共同支出', expenseDesc: '記錄支出並掌握每筆費用。', recentExpenses: '近期支出', records: '{count} 筆', uncategorized: '未分類', noExpenses: '還沒有支出', noExpensesDesc: '新增第一筆支出來開始記錄。', editExpense: '編輯支出', createExpense: '新增支出', item: '項目', itemPlaceholder: '例如：午餐', category: '分類', amount: '金額', payer: '付款人', myself: '我自己', date: '日期', notes: '備註', remove: '移除', removeExpenseConfirm: '確定要移除「{name}」嗎？', sharedRecordWarning: '這筆資料來自「{group}」，儲存後會同步更新群組帳目。', splitMode: '分攤方式', splitEqual: '平均分攤', splitAmount: '固定金額', splitPercentage: '百分比', participants: '參與者', splitTotal: '分攤合計', splitRemainder: '尾差', splitValid: '分攤金額正確', splitInvalidAmount: '分攤總和必須等於支出金額', splitInvalidPercentage: '百分比總和必須為 100%', basisPointsHint: '請輸入百分比',
  subscriptionPersonal: '個人訂閱', subscriptionGroup: '群組訂閱', subscriptionDesc: '以第一個扣款日推算週期，並可排程停止。', allSubscriptions: '所有訂閱', noSubscriptions: '還沒有訂閱', noSubscriptionsDesc: '加入第一筆固定扣款。', editSubscription: '編輯訂閱', createSubscription: '新增訂閱', name: '名稱', namePlaceholder: '例如 Netflix', cycle: '週期', status: '狀態', monthly: '每月', quarterly: '每季', yearly: '每年', firstBilling: '第一個扣款日', nextBilling: '下次扣款', stop: '停止訂閱', cancelStop: '取消停止排程', stopSubscription: '排程停止訂閱', chooseFinalBilling: '選擇最後一期扣款日', loadMore: '載入更多期數', noBillingDates: '沒有可選的扣款日期', finalBilling: '最後一期', deleteSubscriptionConfirm: '確定刪除「{name}」？', active: '啟用', paused: '暫停', cancelled: '已取消', ending: '即將停止', ended: '已結束',
  membersInvites: '成員與邀請', membersDesc: '邀請連結有效七天，只能由相同 Email 的帳號接受一次。', groupMembers: '群組成員', unnamedMember: '未命名成員', owner: '擁有者', member: '成員', thisMember: '此成員', removeMemberConfirm: '確定要移除「{name}」？', noMemberData: '沒有成員資料', noMemberDataDesc: '進入群組後即可查看。', inviteMember: '邀請新成員', sendInvitation: '寄送邀請', invitationHistory: '邀請紀錄', resend: '重送', revoke: '撤銷', noInvitations: '尚無邀請紀錄。', memberManagement: '成員管理', ownerOnly: '只有群組擁有者可以邀請或移除成員。', developmentLink: '開發測試連結', pending: '待接受', deliveryFailed: '寄送失敗', accepted: '已接受', revoked: '已撤銷', expired: '已過期', invitation: '邀請', joinGroup: '加入 SubFlow 群組', inviteDesc: '系統會確認目前登入帳號的 Email 與邀請對象一致。', acceptInvitation: '接受邀請', joined: '已加入，正在前往群組…',
  balances: '成員餘額', settlements: '還款紀錄', recordSettlement: '記錄還款', fromMember: '付款人', toMember: '收款人', settlementDate: '還款日期', noSettlements: '尚無還款紀錄', noBalances: '目前沒有應收應付', deleteSettlementConfirm: '確定刪除這筆還款紀錄嗎？',
  confirm: '確認', delete: '刪除', networkError: '網路連線失敗，請稍後重試', invalidResponse: '伺服器回應格式錯誤', requestFailed: '請求失敗', invalidRequest: '輸入資料不正確', conflict: '資料狀態衝突', notFound: '找不到指定資源', internalError: '服務暫時無法處理請求', forbiddenError: '沒有權限執行此操作',
  languageZhMarker: '繁', languageEnMarker: 'A', groupTimezone: '群組時區', groupTimezoneDesc: '群組月份、訂閱週期與共同帳務以此時區為準。', originalTimezone: '原始群組時間：{date} · {timezone}', yourTimezone: '你的時區：{timezone}', groupTimezoneValue: '群組帳務時區：{timezone}',
  search:'搜尋',add:'新增',addCategory:'新增分類',rateUnavailable:'找不到可用匯率，請輸入手動匯率',exchangeRate:'匯率',automaticRate:'系統匯率',manualRate:'手動匯率',rateLoading:'正在取得系統匯率…',rateStale:'使用最近可用資料',rateManualHint:'此匯率將隨這筆紀錄一併保存。',rateManualInvalid:'請輸入大於 0 的手動匯率。',sameCurrencyRate:'相同幣別，無需換匯。',convertedAmount:'換算後統計金額：{amount}',reportingAmount:'統計金額',originalAmount:'原始金額',reportingCurrency:'統計幣別',rateEffectiveDate:'匯率日期',rateProvider:'匯率來源',currencyChangeConfirm:'將重算 {count} 筆群組紀錄，確定變更統計幣別？',currencyChangeBlocked:'尚有 {count} 筆紀錄缺少匯率，無法變更統計幣別。',category_food_dining:'餐飲',category_transport:'交通',category_housing:'住家',category_utilities:'水電與帳單',category_shopping:'購物',category_entertainment:'娛樂',category_health:'健康',category_education:'教育',category_travel:'旅行',category_insurance:'保險',category_software_digital:'軟體與數位服務',category_memberships:'會員',category_taxes_fees:'稅務與手續費',category_gifts_donations:'禮物與捐款',category_other:'其他',
  setup:'\u521d\u59cb\u5316\u8a2d\u5b9a', setupTitle:'\u5efa\u7acb\u7ba1\u7406\u54e1', setupDesc:'\u8a2d\u5b9a\u7b2c\u4e00\u4f4d\u7ba1\u7406\u54e1\u8207\u7cfb\u7d71\u9810\u8a2d\u503c\u3002\u5b8c\u6210\u5f8c\u6b64\u7a0b\u5e8f\u5c07\u6c38\u4e45\u95dc\u9589\u3002', siteName:'\u7ad9\u9ede\u540d\u7a31', allowRegistration:'\u5141\u8a31\u65b0\u4f7f\u7528\u8005\u8a3b\u518a', setupLinkRequired:'\u9700\u8981\u521d\u59cb\u5316\u9023\u7d50', setupLinkRequiredDesc:'\u8acb\u4f7f\u7528\u4f3a\u670d\u5668\u9996\u6b21\u555f\u52d5\u65e5\u8a8c\u4e2d\u7684\u4e00\u6b21\u6027\u521d\u59cb\u5316\u9023\u7d50\u3002', completeSetup:'\u5b8c\u6210\u521d\u59cb\u5316', showPassword:'\u986f\u793a\u5bc6\u78bc', hidePassword:'\u96b1\u85cf\u5bc6\u78bc', setupCompleted:'\u521d\u59cb\u5316\u5b8c\u6210', setupRedirecting:'\u6b63\u5728\u958b\u555f\u4f60\u7684\u8ca1\u52d9\u7e3d\u89bd\u2026',
} as const

export type MessageKey = keyof typeof zhTW
