<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useWorkspaceStore } from '../stores/workspace'
import BaseInput from '../components/BaseInput.vue'
import BaseCombobox from '../components/BaseCombobox.vue'
import ConfirmDialog from '../components/ConfirmDialog.vue'
import { useI18n } from '../i18n'
import type { AccessRole } from '../api/types'
import { roleLabel } from '../role'

const workspace=useWorkspaceStore(),{tr}=useI18n()
const editing=ref<AccessRole|undefined>(), removing=ref<AccessRole|undefined>()
const form=reactive({name:'',category:'',permissions:[] as string[]})
const permissionOptions=['group.view','group.settings.manage','group.members.manage','group.roles.manage','group.audit.read','ledger.expenses.read','ledger.expenses.write','ledger.records.historical_write','ledger.expenses.delete','ledger.subscriptions.read','ledger.subscriptions.write','ledger.subscriptions.delete','ledger.settlements.read','ledger.settlements.write','ledger.settlements.delete','categories.manage']
const roleCategories=computed(()=>[...new Set(workspace.groupRoles.map(role=>role.category).filter(Boolean))])
const grouped=computed(()=>{const values=new Map<string,AccessRole[]>();for(const role of workspace.groupRoles){const key=role.category||tr('ungroupedRoles');values.set(key,[...(values.get(key)||[]),role])}return values})
function canManage(){return workspace.groupPermissions.includes('*')||workspace.groupPermissions.includes('group.roles.manage')}
function open(role?:AccessRole){editing.value=role??{id:'',scope:'group',groupId:'',name:'',category:'',key:'',permissions:[],protected:false,createdAt:'',updatedAt:''};Object.assign(form,{name:role?.name||'',category:role?.category||'',permissions:[...(role?.permissions||[])]})}
function toggle(permission:string){form.permissions=form.permissions.includes(permission)?form.permissions.filter(value=>value!==permission):[...form.permissions,permission]}
async function save(){if(!form.name.trim())return;if(editing.value?.id)await workspace.updateGroupRole(editing.value.id,{name:form.name,category:form.category,permissions:form.permissions});else await workspace.createGroupRole({name:form.name,category:form.category,permissions:form.permissions});editing.value=undefined}
async function remove(){if(removing.value){await workspace.deleteGroupRole(removing.value.id);removing.value=undefined}}
onMounted(()=>void workspace.loadGroupRoles())
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">{{tr('roleManagement')}}</p><h1>{{tr('roleManagement')}}</h1><p>{{tr('groupRoleManagementDesc')}}</p></div><button v-if="canManage()" class="primary" @click="open()">{{tr('createRole')}}</button></div><section v-for="[category,roles] in grouped" :key="category" class="card role-group"><h2>{{category}}</h2><article v-for="role in roles" :key="role.id" class="data-row role-row"><div class="grow"><strong>{{roleLabel(role,tr)}}</strong><small>{{role.permissions.map(value=>tr(`permission_${value.replaceAll('.','_')}` as never)).join(' · ')||tr('noPermissions')}}</small></div><span v-if="role.protected" class="pill">{{tr('protectedRole')}}</span><button v-if="canManage()&&!role.protected" class="ghost" @click="open(role)">{{tr('edit')}}</button><button v-if="canManage()&&!role.protected" class="ghost danger-text" @click="removing=role">{{tr('delete')}}</button></article></section><section v-if="editing" class="card role-editor"><div class="form-section"><h2>{{editing.id?tr('editRole'):tr('createRole')}}</h2><BaseInput v-model="form.name" :label="tr('roleName')" required/><BaseCombobox v-model="form.category" :options="roleCategories" :label="tr('roleGroup')" :placeholder="tr('ungroupedRoles')" :help="tr('roleGroupHelp')"/></div><fieldset class="permission-options form-section"><legend>{{tr('permissions')}}</legend><label v-for="permission in permissionOptions" :key="permission" class="permission-option"><input type="checkbox" :checked="form.permissions.includes(permission)" @change="toggle(permission)"><span><strong>{{tr(`permission_${permission.replaceAll('.','_')}` as never)}}</strong><small>{{tr(`permissionDesc_${permission.replaceAll('.','_')}` as never)}}</small></span></label></fieldset><div class="form-actions"><button class="primary" :disabled="!workspace.online" :title="workspace.online?'':tr('offlineActionDisabled')" @click="save">{{tr('saveChanges')}}</button><button class="ghost" @click="editing=undefined">{{tr('cancel')}}</button></div></section><p v-if="!workspace.groupRoles.length" class="empty-inline">{{tr('noRoles')}}</p><ConfirmDialog :open="!!removing" :title="tr('deleteRoleConfirm',{name:removing?roleLabel(removing,tr):''})" danger @cancel="removing=undefined" @confirm="remove"/></section></template>
<style scoped>.role-group{display:grid;gap:12px}.role-row{align-items:flex-start}.role-row small{display:block;line-height:1.5}.role-editor{display:grid;gap:24px;margin-top:24px}.form-section{display:grid;gap:14px}.role-editor .permission-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:0;padding:14px;border:1px solid var(--line);border-radius:12px}.permission-options legend{padding:0 5px;color:var(--muted);font-size:12px;font-weight:800}.permission-option{display:flex;align-items:flex-start;gap:8px;min-height:58px;padding:7px 8px;border-radius:8px;background:var(--surface-soft);font-size:12px;font-weight:650}.permission-option input[type=checkbox]{width:16px;height:16px;flex:0 0 auto;margin:0;accent-color:var(--brand)}.form-actions{display:flex;gap:10px;flex-wrap:wrap}@media(max-width:720px){.role-editor .permission-options{grid-template-columns:1fr}}@media(max-width:620px){.role-row{grid-template-columns:1fr}.role-row .ghost{width:100%}}</style>
