<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { pb } from '../pocketbase'
import { ApiClient } from '../api/client'
import type { Share, ShareAccessMode, ShareRangeMode } from '../api/types'

const route=useRoute(), client=new ApiClient(()=>pb.authStore.token,()=>{})
const groupId=computed(()=>String(route.params.groupId||'')), isGroup=computed(()=>!!groupId.value)
const shares=ref<Share[]>([]), busy=ref(false), error=ref(''), copied=ref('')
const editing=ref<Share|undefined>()
const form=reactive({name:'',accessMode:'link' as ShareAccessMode,password:'',viewerEmails:'',enabled:true,expiresAt:'',rangeMode:'all' as ShareRangeMode,rollingDays:30,startsOn:'',endsOn:'',showSummary:true,showExpenses:true,showSubscriptions:true,showSettlements:true,showIdentities:false,showNotes:false})
const base=computed(()=>isGroup.value?`/groups/${groupId.value}/shares`:'/personal/shares')
function reset(value?:Share){editing.value=value;Object.assign(form,{name:value?.name||'',accessMode:value?.accessMode||'link',password:'',viewerEmails:value?.viewers?.map(item=>item.email).join('\n')||'',enabled:value?.enabled??true,expiresAt:value?.expiresAt?.slice(0,10)||'',rangeMode:value?.rangeMode||'all',rollingDays:value?.rollingDays||30,startsOn:value?.startsOn?.slice(0,10)||'',endsOn:value?.endsOn?.slice(0,10)||'',showSummary:value?.showSummary??true,showExpenses:value?.showExpenses??true,showSubscriptions:value?.showSubscriptions??true,showSettlements:value?.showSettlements??true,showIdentities:value?.showIdentities??false,showNotes:value?.showNotes??false})}
function payload(){return {...form,expiresAt:form.expiresAt?new Date(`${form.expiresAt}T23:59:59`).toISOString():'',startsOn:form.startsOn?new Date(`${form.startsOn}T00:00:00`).toISOString():'',endsOn:form.endsOn?new Date(`${form.endsOn}T00:00:00`).toISOString():'',viewerEmails:form.viewerEmails.split(/[\n,]/).map(value=>value.trim()).filter(Boolean)}}
async function load(){busy.value=true;error.value='';try{shares.value=(await client.get<Share[]>(base.value)).data}catch(reason){error.value=reason instanceof Error?reason.message:'Unable to load shares'}finally{busy.value=false}}
async function save(){busy.value=true;error.value='';try{if(editing.value){await client.patch<Share>(`${base.value}/${editing.value.id}`,payload())}else{const result=await client.post<Share & {url?:string}>(base.value,payload());if(result.data.url)await copy(result.data.url)}reset();await load()}catch(reason){error.value=reason instanceof Error?reason.message:'Unable to save share'}finally{busy.value=false}}
async function remove(value:Share){if(!confirm(`Delete ${value.name}?`))return;await client.delete(`${base.value}/${value.id}`);await load()}
async function rotate(value:Share){const result=await client.post<Share & {url:string}>(`${base.value}/${value.id}/rotate`);await copy(result.data.url);await load()}
async function copy(value:string){const url=new URL(value,window.location.origin).toString();await navigator.clipboard?.writeText(url);copied.value=url;setTimeout(()=>copied.value='',3000)}
onMounted(load);watch(groupId,load)
</script>
<template><section class="page share-manager"><div class="page-heading"><div><p class="eyebrow">{{isGroup?'Group':'Personal'}} ledger</p><h1>Share pages</h1><p>Create private, password-protected, or account-restricted read-only ledger links.</p></div><button class="primary" @click="reset()">Create share</button></div>
  <p v-if="error" class="notice danger">{{error}}</p><p v-if="copied" class="notice success">Link copied: {{copied}}</p>
  <section v-if="editing!==undefined" class="card form-card"><h2>{{editing?.id?'Edit share':'New share'}}</h2><form @submit.prevent="save"><label>Name<input v-model="form.name" required maxlength="120" placeholder="Trip expenses"></label><label>Access<select v-model="form.accessMode"><option value="link">Private link</option><option value="password">Link + password</option><option value="accounts">Specified SubFlow accounts</option></select></label><label v-if="form.accessMode==='password'">{{editing?.id?'New password (leave blank to keep)':'Password'}}<input v-model="form.password" type="password" :required="!editing?.id" minlength="8"></label><label v-if="form.accessMode==='accounts'">Allowed account emails<textarea v-model="form.viewerEmails" rows="3" placeholder="reader@example.com"></textarea></label><label><input v-model="form.enabled" type="checkbox"> Enabled</label><label>Expires on (optional)<input v-model="form.expiresAt" type="date"></label><label>Date range<select v-model="form.rangeMode"><option value="all">All history</option><option value="rolling">Recent period</option><option value="fixed">Fixed dates</option></select></label><label v-if="form.rangeMode==='rolling'">Recent days<select v-model.number="form.rollingDays"><option :value="30">30 days</option><option :value="90">90 days</option><option :value="365">365 days</option></select></label><div v-if="form.rangeMode==='fixed'" class="two"><label>From<input v-model="form.startsOn" type="date"></label><label>To<input v-model="form.endsOn" type="date"></label></div><fieldset><legend>Content</legend><label><input v-model="form.showSummary" type="checkbox"> Summary</label><label><input v-model="form.showExpenses" type="checkbox"> Expenses</label><label><input v-model="form.showSubscriptions" type="checkbox"> Subscriptions</label><label v-if="isGroup"><input v-model="form.showSettlements" type="checkbox"> Settlements</label><label><input v-model="form.showIdentities" type="checkbox"> Names and payers</label><label><input v-model="form.showNotes" type="checkbox"> Notes</label></fieldset><div class="form-actions"><button class="primary" :disabled="busy">Save</button><button class="ghost" type="button" @click="editing=undefined">Cancel</button></div></form></section>
  <section class="card"><p v-if="busy">Loading…</p><div v-for="share in shares" :key="share.id" class="share-row"><div><strong>{{share.name}}</strong><small>{{share.accessMode}} · {{share.enabled?'enabled':'disabled'}} · {{share.rangeMode}}</small></div><div class="row-actions"><button class="ghost" @click="reset(share)">Edit</button><button class="ghost" @click="rotate(share)">Regenerate link</button><button class="ghost danger-text" @click="remove(share)">Delete</button></div></div><p v-if="!busy&&!shares.length" class="empty-inline">No share pages yet.</p></section></section></template>
<style scoped>.share-manager{display:grid;gap:20px}.form-card form{display:grid;gap:14px;max-width:720px}.form-card fieldset{display:flex;flex-wrap:wrap;gap:12px;padding:14px;border:1px solid var(--line);border-radius:12px}.form-card fieldset label{display:flex;gap:6px;align-items:center}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.share-row{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:14px 0;border-bottom:1px solid var(--line)}.share-row small{display:block;color:var(--muted);margin-top:4px}.row-actions{display:flex;flex-wrap:wrap;gap:8px}@media(max-width:650px){.share-row{align-items:flex-start;flex-direction:column}.two{grid-template-columns:1fr}}</style>
