<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { useWorkspaceStore } from '../stores/workspace'
import MoneyValue from '../components/MoneyValue.vue'
import EmptyState from '../components/EmptyState.vue'
import type { BillingCycle, Subscription, SubscriptionStatus } from '../api/types'
import { majorToMinor, minorToInput } from '../api/money'

const workspace = useWorkspaceStore(), route = useRoute(), editingId = ref('')
const personal = computed(() => route.path.startsWith('/personal/'))
const list = computed(() => personal.value ? workspace.personalSubscriptions : workspace.subscriptions)
const currency = computed(() => workspace.currentGroup?.currency || 'TWD')
const form = reactive({ name:'',category:'影音',amount:'',billingCycle:'monthly' as BillingCycle,startsOn:new Date().toISOString().slice(0,10),status:'active' as SubscriptionStatus,notes:'' })
function reset(){editingId.value='';Object.assign(form,{name:'',category:'影音',amount:'',billingCycle:'monthly',startsOn:new Date().toISOString().slice(0,10),status:'active',notes:''})}
function edit(item:Subscription){editingId.value=item.id;Object.assign(form,{name:item.name,category:item.category,amount:minorToInput(item.amountMinor,item.currency),billingCycle:item.billingCycle,startsOn:(item.startsOn||item.nextBilling).slice(0,10),status:item.status,notes:item.notes})}
async function submit(){const input={name:form.name,category:form.category,amountMinor:majorToMinor(form.amount,currency.value),currency:currency.value,billingCycle:form.billingCycle,startsOn:new Date(form.startsOn).toISOString(),status:form.status,notes:form.notes};if(editingId.value)await workspace.updateSubscription(editingId.value,input);else if(personal.value)await workspace.addPersonalSubscription(input);else await workspace.addSubscription(input);reset()}
async function stop(item:Subscription){const value=prompt('選擇最後一期扣款日（YYYY-MM-DD）',item.nextBilling.slice(0,10));if(value)await workspace.stopSubscription(item.id,value)}
async function remove(item:Subscription){if(confirm(`確定刪除「${item.name}」？`)){await workspace.deleteSubscription(item.id);if(editingId.value===item.id)reset()}}
onMounted(()=>{if(personal.value)void workspace.refreshPersonal()})
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">RECURRING</p><h1>{{personal?'個人訂閱':'群組訂閱'}}</h1><p>以第一個扣款日推算週期，並可排程停止。</p></div></div><div class="two-column content-heavy"><div class="card"><div class="card-title"><h2>所有訂閱</h2><span>{{list.length}} 筆</span></div><div v-if="list.length" class="rows"><div v-for="item in list" :key="item.id" class="row"><div class="service-icon">{{item.name.slice(0,1)}}</div><div class="grow"><strong>{{item.name}}</strong><small>{{item.category||'未分類'}} · 下次 {{new Date(item.nextBilling).toLocaleDateString('zh-TW')}} · {{item.lifecycleStatus||item.status}}</small></div><div class="money"><MoneyValue :amount="item.amountMinor" :currency="item.currency"/><small>/ {{item.billingCycle==='monthly'?'月':item.billingCycle==='quarterly'?'季':'年'}}</small></div><button class="ghost" v-if="item.lifecycleStatus!=='ended'&&item.lifecycleStatus!=='cancelled'" @click="stop(item)">停止</button><button class="icon-button" @click="edit(item)">✎</button><button class="icon-button" @click="remove(item)">×</button></div></div><EmptyState v-else title="還沒有訂閱" description="加入第一筆固定扣款。"/></div><form class="card form-card sticky" @submit.prevent="submit"><h2>{{editingId?'編輯訂閱':'新增訂閱'}}</h2><label>名稱<input v-model="form.name" required placeholder="例如 Netflix"></label><div class="form-row"><label>分類<input v-model="form.category"></label><label>金額<input v-model="form.amount" type="number" min="0" step="0.01" required></label></div><div class="form-row"><label>週期<select v-model="form.billingCycle"><option value="monthly">每月</option><option value="quarterly">每季</option><option value="yearly">每年</option></select></label><label>狀態<select v-model="form.status"><option value="active">啟用</option><option value="paused">暫停</option><option value="cancelled">取消</option></select></label></div><label>第一個扣款日<input v-model="form.startsOn" type="date" required></label><label>備註<textarea v-model="form.notes" rows="2"></textarea></label><div class="form-actions"><button class="primary" :disabled="workspace.loading">{{editingId?'儲存變更':'新增訂閱'}}</button><button v-if="editingId" type="button" class="ghost" @click="reset">取消</button></div></form></div></section></template>
