<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { useWorkspaceStore } from '../stores/workspace'
import { useAuthStore } from '../stores/auth'
import MoneyValue from '../components/MoneyValue.vue'
import EmptyState from '../components/EmptyState.vue'
import AppDrawer from '../components/AppDrawer.vue'
import ConfirmDialog from '../components/ConfirmDialog.vue'
import PersonalLedgerNav from '../components/PersonalLedgerNav.vue'
import CurrencySelect from '../components/CurrencySelect.vue'
import CategorySelect from '../components/CategorySelect.vue'
import type { BillingCycle, Subscription, SubscriptionStatus } from '../api/types'
import { majorToMinor, minorToInput } from '../api/money'
import { useI18n } from '../i18n'
import { timezoneLabel } from '../timezone'

const workspace=useWorkspaceStore(),auth=useAuthStore(),route=useRoute(),{tr,formatDate}=useI18n()
const personal=computed(()=>route.name==='personal-subscriptions'),list=computed(()=>personal.value?workspace.personalSubscriptions:workspace.subscriptions)
const drawer=ref(false),editingId=ref(''),pendingDelete=ref<Subscription>(),stopping=ref<Subscription>(),dates=ref<string[]>([]),cursor=ref(''),chosenDate=ref(''),datesLoading=ref(false)
const form=reactive({name:'',category:'',categoryId:'',amount:'',currency:'TWD',rateMode:'automatic' as 'automatic'|'manual',exchangeRate:'',billingCycle:'monthly' as BillingCycle,startsOn:new Date().toISOString().slice(0,10),status:'active' as SubscriptionStatus,notes:''})
const editing=computed(()=>list.value.find(item=>item.id===editingId.value)),sourceGroup=computed(()=>workspace.groups.find(group=>group.id===editing.value?.groupId))
function reset(){editingId.value='';Object.assign(form,{name:'',category:'',categoryId:'',amount:'',currency:workspace.currentGroup?.currency||'TWD',rateMode:'automatic',exchangeRate:'',billingCycle:'monthly',startsOn:new Date().toISOString().slice(0,10),status:'active',notes:''})}
async function loadFormCategories(){await workspace.loadCategories(personal.value&&!editing.value?.groupId?'personal':'group',editing.value?.groupId||workspace.currentGroupId)}
async function create(){reset();await loadFormCategories();drawer.value=true}
async function edit(item:Subscription){editingId.value=item.id;Object.assign(form,{name:item.name,category:item.category,categoryId:item.categoryId||'',amount:minorToInput(item.amountMinor,item.currency),currency:item.currency,rateMode:item.rateMode||'automatic',exchangeRate:item.exchangeRate||'',billingCycle:item.billingCycle,startsOn:(item.startsOn||item.nextBilling).slice(0,10),status:item.status,notes:item.notes});await loadFormCategories();drawer.value=true}
async function addCategory(name:string){const value=await workspace.createCategory(personal.value&&!editing.value?.groupId?'personal':'group',name,editing.value?.groupId||workspace.currentGroupId);form.categoryId=value.id}
async function submit(){const input={name:form.name,category:form.category||'',categoryId:form.categoryId,amountMinor:majorToMinor(form.amount,form.currency),currency:form.currency as Subscription['currency'],rateMode:form.rateMode,exchangeRate:form.exchangeRate,billingCycle:form.billingCycle,startsOn:new Date(`${form.startsOn}T00:00:00`).toISOString(),status:form.status,notes:form.notes};if(editingId.value)await workspace.updateSubscription(editingId.value,input);else if(personal.value)await workspace.addPersonalSubscription(input);else await workspace.addSubscription(input);await workspace.refreshPersonal();drawer.value=false;reset()}
async function loadDates(more=false){if(!stopping.value)return;datesLoading.value=true;try{const result=await workspace.billingDates(stopping.value.id,more?cursor.value:'');dates.value=more?[...dates.value,...result.dates]:result.dates;cursor.value=result.nextCursor||'';if(!chosenDate.value)chosenDate.value=dates.value[0]||''}finally{datesLoading.value=false}}
async function openStop(item:Subscription){stopping.value=item;dates.value=[];cursor.value='';chosenDate.value='';await loadDates()}
async function confirmStop(){if(!stopping.value||!chosenDate.value)return;await workspace.stopSubscription(stopping.value.id,chosenDate.value);stopping.value=undefined}
async function cancelStop(item:Subscription){await workspace.cancelSubscriptionStop(item.id)}
async function remove(){if(!pendingDelete.value)return;await workspace.deleteSubscription(pendingDelete.value.id);await workspace.refreshPersonal();pendingDelete.value=undefined}
function statusKey(item:Subscription){return (item.lifecycleStatus||item.status) as 'active'}
function cycleKey(item:Subscription){return item.billingCycle as 'monthly'}
function recordCategory(item:Subscription){const category=item.categoryInfo;if(category?.systemKey)return tr((`category_${category.systemKey}`) as Parameters<typeof tr>[0]);return category?.customName||item.category||tr('uncategorized')}
function viewerTimezone(){return auth.record?.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'}
function itemGroup(item:Subscription){return workspace.groups.find(group=>group.id===item.groupId)}
function viewerDate(value:string){return formatDate(value,{dateStyle:'medium',timeZone:viewerTimezone()})}
function originalTime(item:Subscription,value=item.nextBilling){const group=itemGroup(item);return group?tr('originalTimezone',{date:formatDate(value,{dateStyle:'medium',timeZone:group.timezone}),timezone:timezoneLabel(group.timezone,value)}):''}
onMounted(()=>{if(personal.value)void workspace.refreshPersonal()})
</script>

<template><section class="page ledger-page"><PersonalLedgerNav v-if="personal"/><div class="page-heading"><div><p class="eyebrow">{{tr('subscriptions')}}</p><h1>{{tr(personal?'subscriptionPersonal':'subscriptionGroup')}}</h1><p>{{tr('subscriptionDesc')}}</p></div><button class="primary" @click="create">{{tr('createSubscription')}}</button></div>
  <section class="card data-card"><div class="card-title"><h2>{{tr('allSubscriptions')}}</h2><span>{{tr('records',{count:list.length})}}</span></div><div v-if="list.length" class="data-table subscription-table"><div class="data-table-head"><span>{{tr('name')}}</span><span>{{tr('source')}}</span><span>{{tr('nextBilling')}}</span><span>{{tr('cycle')}}</span><span>{{tr('status')}}</span><span>{{tr('amount')}}</span><span></span></div><article v-for="item in list" :key="item.id" class="data-table-row"><div class="item-cell"><span class="service-icon">{{item.name.slice(0,1)}}</span><span><strong>{{item.name}}</strong><small>{{recordCategory(item)}}</small></span></div><span><span class="source-badge" :class="{shared:item.groupId}">{{itemGroup(item)?.name||tr('privateRecord')}}</span></span><span class="timezone-date"><strong>{{viewerDate(item.nextBilling)}}</strong><small v-if="item.groupId">{{originalTime(item)}}</small></span><span>{{tr(cycleKey(item))}}</span><span class="pill">{{tr(statusKey(item))}}</span><span class="money-stack"><MoneyValue :amount="item.amountMinor" :currency="item.currency"/><small v-if="item.baseCurrency&&item.baseCurrency!==item.currency">{{tr('reportingAmount')}}: <MoneyValue :amount="item.baseAmountMinor" :currency="item.baseCurrency"/></small><small v-if="item.exchangeRate">{{tr('exchangeRate')}} {{item.exchangeRate}}</small></span><span class="row-actions"><button v-if="item.endsOn&&item.lifecycleStatus==='ending'" class="ghost" @click="cancelStop(item)">{{tr('cancelStop')}}</button><button v-else-if="item.lifecycleStatus!=='ended'&&item.lifecycleStatus!=='cancelled'" class="ghost" @click="openStop(item)">{{tr('stop')}}</button><button class="icon-button" :aria-label="tr('edit')" @click="edit(item)">✎</button><button class="icon-button" :aria-label="tr('delete')" @click="pendingDelete=item">×</button></span></article></div><EmptyState v-else :title="tr('noSubscriptions')" :description="tr('noSubscriptionsDesc')"/></section>
  <AppDrawer :open="drawer" :title="tr(editingId?'editSubscription':'createSubscription')" @close="drawer=false"><form class="form-card" @submit.prevent="submit">
    <div v-if="editing?.groupId&&personal" class="notice inline">{{tr('sharedRecordWarning',{group:sourceGroup?.name||tr('groups')})}}</div><div v-if="sourceGroup||(!personal&&workspace.currentGroup)" class="timezone-notice">{{tr('yourTimezone',{timezone:timezoneLabel(viewerTimezone())})}}<br>{{tr('groupTimezoneValue',{timezone:timezoneLabel((sourceGroup||workspace.currentGroup)?.timezone||'UTC')})}}</div>
    <label>{{tr('name')}}<input v-model="form.name" required :placeholder="tr('namePlaceholder')"></label>
    <div class="form-row"><label>{{tr('category')}}<CategorySelect v-model="form.categoryId" :categories="workspace.categories" @create="addCategory"/></label><label>{{tr('amount')}}<input v-model="form.amount" type="number" min="0" step="0.01" required></label></div>
    <div class="form-row"><label>{{tr('currency')}}<CurrencySelect v-model="form.currency" :currencies="workspace.currencies"/></label><label>{{tr('cycle')}}<select v-model="form.billingCycle"><option value="monthly">{{tr('monthly')}}</option><option value="quarterly">{{tr('quarterly')}}</option><option value="yearly">{{tr('yearly')}}</option></select></label></div>
    <div class="form-row"><label>{{tr('exchangeRate')}}<select v-model="form.rateMode"><option value="automatic">{{tr('automaticRate')}}</option><option value="manual">{{tr('manualRate')}}</option></select><input v-if="form.rateMode==='manual'" v-model="form.exchangeRate" inputmode="decimal" required></label><label>{{tr('firstBilling')}}<input v-model="form.startsOn" type="date" required></label></div>
    <div class="form-row"><label>{{tr('status')}}<select v-model="form.status"><option value="active">{{tr('active')}}</option><option value="paused">{{tr('paused')}}</option><option value="cancelled">{{tr('cancelled')}}</option></select></label></div><label>{{tr('notes')}}<textarea v-model="form.notes" rows="3"></textarea></label><div class="form-actions"><button type="button" class="ghost" @click="drawer=false">{{tr('cancel')}}</button><button class="primary" :disabled="workspace.loading">{{tr(editingId?'saveChanges':'createSubscription')}}</button></div></form></AppDrawer>
  <Teleport to="body"><div v-if="stopping" class="modal-backdrop" @click.self="stopping=undefined"><section class="billing-dialog" role="dialog" aria-modal="true" :aria-label="tr('stopSubscription')"><header><div><h2>{{tr('stopSubscription')}}</h2><p>{{stopping.name}} · {{tr('chooseFinalBilling')}}</p></div><button class="icon-button" :aria-label="tr('close')" @click="stopping=undefined">×</button></header><div v-if="dates.length" class="billing-dates"><label v-for="date in dates" :key="date" :class="{selected:chosenDate===date}"><input v-model="chosenDate" type="radio" :value="date"><span><strong>{{viewerDate(date)}}</strong><small>{{tr('finalBilling')}}</small><small v-if="stopping.groupId">{{originalTime(stopping,date)}}</small></span></label></div><EmptyState v-else :title="tr('noBillingDates')" :description="tr('subscriptionDesc')"/><button v-if="cursor" class="ghost wide" :disabled="datesLoading" @click="loadDates(true)">{{tr('loadMore')}}</button><div class="form-actions"><button class="ghost" @click="stopping=undefined">{{tr('cancel')}}</button><button class="primary" :disabled="!chosenDate" @click="confirmStop">{{tr('confirm')}}</button></div></section></div></Teleport>
  <ConfirmDialog :open="!!pendingDelete" :title="pendingDelete?tr('deleteSubscriptionConfirm',{name:pendingDelete.name}):''" danger @cancel="pendingDelete=undefined" @confirm="remove"/>
</section></template>
